### PR TITLE
Support assuming roles with a Path

### PR DESCRIPTION
**Pull request by jpb**
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-friendly-names

### CODE REVIEW

**Comment by ryan-lane** [comment]
Thanks for the PR! I'll need to look through the code to make sure this is going to work as expected. At a quick glance it looks mostly good.

**Comment by jpb** [comment]
Hey @ryan-lane have you had a chance to double check this PR?

**Comment by ryan-lane** [comment]
Sorry! Slipped off my radar. Let me take a look now.

**Comment by rsrchboy** [comment]
...and now? :)

**Comment by ryan-lane** [comment]
Sorry, I'm the worst. I got a chance to verify this. Merging in now.

**Comment by ryan-lane** [comment]
Released in 1.10.0

**Pull request merged**
